name: 'Tari jniLibs'
description: 'Builds Tari android JNI libraries from source'
inputs:
  platforms:
    description: 'An array of platforms for which to build libwallet. Separate multiple platforms by spaces.'
    required: false
    default: 'aarch64-linux-android'
  level:
    description: 'The android SDK level to use'
    required: false
    default: '24'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.platforms }}
    - ${{ inputs.level }}
