name: 'Tari jniLibs'
description: 'Builds Tari android JNI libraries from source'
inputs:
  platforms:
    description: 'An array of platforms for which to build libwallet. Separate multiple platforms with a semicolon.'
    required: false
    default: 'x86_64-linux-android;aarch64-linux-android;armv7-linux-androideabi'
  level:
    description: 'The android SDK level to use'
    required: false
    default: '24'
  version:
    description: 'The version tag to use in the build'
    required: false
    default: ${{ github.ref }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.platforms }}"
    - "${{ inputs.level }}"
    - '/github/workspace'
    - "${{ inputs.version }}"
